---
# This playbook deploys the whole application stack in this site.

- name: Uninstall task
  hosts: common
  gather_facts: false
  roles:
    - common
    - uninstall
  tags:
    - uninstall
    - remove
  environment: &common_play_environment
    HOME: "{{ common_target_home | default(ansible_user_dir | default('')) }}"
    PATH: "{{ common_target_path | default(common_fallback_path) }}"

- name: Install task
  hosts: common
  gather_facts: false
  roles:
    - common
    - install
  tags:
    - install
    - deploy
  environment:
    <<: *common_play_environment
    PIP_INDEX_URL: "{{ common_pip_index_url }}"
    PASSPHRASE: test

- name: K3s task
  hosts: masters,slaves
  gather_facts: false
  roles:
    - common
    - k3s
  tags:
    - k3s
  environment:
    <<: *common_play_environment

- name: Kubernetes task
  hosts: masters,slaves
  gather_facts: false
  roles:
    - common
    - kubernetes
  tags:
    - k8s
    - kubernetes
  environment:
    <<: *common_play_environment
