---
# This playbook deploys the whole application stack in this site.

- name: Uninstall task
  hosts: common
  gather_facts: false
  roles:
    - common
    - uninstall
  tags:
    - uninstall
    - remove
  environment:
    HOME: "{{ ansible_user_dir | default('') }}"
    PATH: "{{ ansible_env.PATH | default('/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin:/opt/homebrew/bin') }}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin:/opt/homebrew/bin:{{ ansible_user_dir | default('') }}/.lima/.bin"

- name: Install task
  hosts: common
  gather_facts: false
  roles:
    - common
    - install
  tags:
    - install
    - deploy
  environment:
    HOME: "{{ ansible_user_dir | default('') }}"
    PIP_INDEX_URL: "{{ common_pip_index_url }}"
    PATH: "{{ ansible_env.PATH | default('/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin:/opt/homebrew/bin') }}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin:/opt/homebrew/bin:/usr/local/n/bin:{{ ansible_user_dir | default('') }}/.local/bin:{{ ansible_user_dir | default('') }}/.lima/.bin::{{ ansible_user_dir | default('') }}/.cargo/bin"
    PASSPHRASE: test

- name: K3s task
  hosts: masters,slaves
  gather_facts: false
  roles:
    - common
    - k3s
  tags:
    - k3s

- name: Kubernetes task
  hosts: masters,slaves
  gather_facts: false
  roles:
    - common
    - kubernetes
  tags:
    - k8s
    - kubernetes
