---
# This playbook deploys the whole application stack in this site.

- name: uninstall
  hosts: common
  roles:
    - common
    - uninstall
  tags:
    - uninstall
    - remove

- name: install
  hosts: common
  roles:
    - common
    - install
  tags:
    - install
    - deploy
  environment:
    PIP_INDEX_URL: "{{PIP_INDEX_URL}}"
