---
# This playbook deploys the whole application stack in this site.

- name: uninstall_task
  hosts: common
  gather_facts: False
  roles:
    - common
    - uninstall
  tags:
    - uninstall
    - remove
  environment:
    PATH: "${PATH}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin"

- name: install_task
  hosts: common
  gather_facts: False
  roles:
    - common
    - install
  tags:
    - install
    - deploy
  environment:
    PIP_INDEX_URL: "{{ PIP_INDEX_URL }}"
    PATH: "${PATH}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin"
    PASSPHRASE: test

- name: k3s_task
  hosts: masters,slaves
  gather_facts: False
  roles:
    - common
    - k3s
  tags:
    - k3s

- name: kubernetes_task
  hosts: masters,slaves
  gather_facts: False
  roles:
    - common
    - kubernetes
  tags:
    - k8s
    - kubernetes
