---
# vars file for kubernetes

HOME_ROOT: "{{ansible_user_dir}}" # 登陆用户的 home 目录
KUBEADM_CONFIG_PATH: "{{HOME_ROOT}}/kubeadm.conf"
CNI_PLUGINS_DIRECTOR_ON_LINUX: "/opt/cni/bin"
CNI_PLUGINS_PATH_ON_LINUX: "{{HOME_ROOT}}/cni-plugins-linux-amd64-v0.8.2.tgz"
CNI_PLUGINS_URL_ON_LINUX: "https://github.com/containernetworking/plugins/releases/download/v0.8.2/cni-plugins-linux-amd64-v0.8.2.tgz"
