---
# defaults file for install

install_notify_access_token: "xxxx"
install_redis_password: "xxxx"
install_mongo_ro_password: "xxxx"
install_mongo_rw_password: "xxxx"
install_mongo_user_admin_password: "xxxx"
install_mongo_admin_password: "xxxx"
install_mongo_root_password: "xxxx"
