---

- name: stop docker
  service: name={{ item.name }} state={{ item.state }} enabled={{ item.enabled }}
  with_items:
    - name: 'docker'
      enabled: 'no'
      state: 'stopped'
  ignore_errors: True
  tags:
    - remove_docker
  when: is_linux_os

- name: uninstall docker on Redhat
  yum:
    name: "{{ item }}"
    state: absent
    update_cache: true
  with_items:
    - docker-engine
    - docker-ce
    - docker-ce-cli
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-buildx-plugin
    - docker-compose-plugin
    - containerd.io
  tags:
    - remove_docker
  when: is_centos_os

- name: uninstall docker on Ubuntu
  apt:
    pkg: "{{ item }}"
    state: absent
    update_cache: true
  with_items:
    - "docker"
    - "docker-io"
    - "docker.io"
    - "docker-ce"
    - "docker-ce-cli"
    - "docker-engine"
    - "containerd.io"
    - "containerd"
    - "runc"
  become: true
  become_method: sudo
  ignore_errors: True
  tags:
    - remove_docker
  when: is_ubuntu_os

- name: uninstall docker docker-machine docker-compose on macOS
  shell: "brew cask uninstall {{ item }}  --force || brew uninstall {{ item }} --force"
  with_items:
    - "docker"
    - "docker-machine"
    - "docker-compose"
    - "docker-completion"
    - "docker-compose-completion"
    - "docker-machine-completion"
  ignore_errors: True
  tags:
    - remove_docker
  when: is_mac_os

- name: remove docker directory
  file:
    path: "{{ item }}"
    state: absent
    force: true
  with_items:
    - "/var/lib/docker"
    - "/var/run/docker"
    - "/run/docker"
    - "/etc/docker"
    - "/usr/libexec/docker"
    - "/etc/apparmor.d/docker"
    - "/etc/yum.repos.d/docker-ce.repo"
    - "/var/run/docker.sock"
    - "/usr/local/bin/docker-compose"
    - "{{ HOME_ROOT }}/Library/Caches/com.docker.docker"
    - "{{ HOME_ROOT }}/Library/Containers/com.docker.docker"
    - "{{ HOME_ROOT }}/Library/Containers/com.docker.helper"
  become: true
  become_method: sudo
  tags:
    - remove_docker
