---
# tasks file for uninstall

- name: 执行 zsh 卸载任务
  ansible.builtin.import_tasks: zsh.yml
  tags:
    - remove_zsh

- name: 执行 Docker 卸载任务
  ansible.builtin.import_tasks: docker.yml
  tags:
    - remove_docker

- name: 执行初始化软件卸载任务
  ansible.builtin.import_tasks: initialize.yml
  tags:
    - remove_initialize

- name: 执行 Node.js 卸载任务
  ansible.builtin.import_tasks: nodejs.yml
  tags:
    - remove_nodejs

- name: 执行 Go 卸载任务
  ansible.builtin.import_tasks: golang.yml
  tags:
    - remove_golang

- name: 执行 Java 卸载任务
  ansible.builtin.import_tasks: java.yml
  tags:
    - remove_java

- name: 执行 Python Virtualenv 卸载任务
  ansible.builtin.import_tasks: virtualenv.yml
  tags:
    - remove_virtualenv
