---
# tasks file for uninstall

- name: 执行 zsh 卸载任务
  ansible.builtin.include_tasks: zsh.yml
  tags:
    - always

- name: 执行 Docker 卸载任务
  ansible.builtin.include_tasks: docker.yml
  tags:
    - always

- name: 执行初始化软件卸载任务
  ansible.builtin.include_tasks: initialize.yml
  tags:
    - always

- name: 执行 Node.js 卸载任务
  ansible.builtin.include_tasks: nodejs.yml
  tags:
    - always

- name: 执行 Go 卸载任务
  ansible.builtin.include_tasks: golang.yml
  tags:
    - always

- name: 执行 Java 卸载任务
  ansible.builtin.include_tasks: java.yml
  tags:
    - always

- name: 执行 Python Virtualenv 卸载任务
  ansible.builtin.include_tasks: virtualenv.yml
  tags:
    - always
