---
# tasks file for uninstall

- include_tasks: zsh.yml
- include_tasks: docker.yml

- name: uninstall brew on macOS
  shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"'
  tags:
    - remove_brew
  when: is_mac_os and ansible_user_id != "root"

- name: uninstall nvm npm and node
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ HOME_ROOT }}/.nvm"
    - "{{ HOME_ROOT }}/.npm"
    - "{{ HOME_ROOT }}/.yarn"
    - "{{ HOME_ROOT }}/.pnpm-state "
    - "{{ HOME_ROOT }}/.node-gyp"
    - "{{ HOME_ROOT }}/.npminstall_tarball"
    - "/usr/local/n"
    - "/usr/local/bin/node"
    - "/usr/local/bin/npm"
    - "/usr/local/bin/n"
    - "/usr/local/lib/node_modules"
  become: true
  become_method: sudo
  tags:
    - remove_nodejs

- name: uninstall go
  file:
    path: "{{ GOROOT }}"
    state: absent
  become: true
  become_method: sudo
  tags:
    - remove_golang

- name: remove java on RedHat
  shell: "rpm -qa | grep java | xargs rpm -e --noscripts"
  ignore_errors: True
  become: true
  become_method: sudo
  tags:
    - remove_java
  when: is_centos_os

- name: uninstall java
  file:
    path: "{{ JAVA_HOME }}"
    state: absent
  become: true
  become_method: sudo
  tags:
    - remove_java
