---
# tasks file for uninstall

- include: zsh.yml
- include: docker.yml
- include: k3s.yml

- name: uninstall brew on macOS
  shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"'
  tags:
    - remove_brew
  when: is_mac_os and ansible_user_id != "root"

- name: uninstall nvm npm and node
  file:
    path: "{{ HOME_ROOT }}/{{ item }}"
    state: absent
  with_items:
    - .nvm
    - .npm
    - .node-gyp
    - .npminstall_tarball
  become: yes
  become_method: sudo
  tags:
    - remove_nodejs

- name: uninstall go
  file:
    path: "{{ GOROOT }}"
    state: absent
  become: yes
  become_method: sudo
  tags:
    - remove_golang

- name: remove java on RedHat
  shell: "rpm -qa | grep java | xargs rpm -e --noscripts"
  ignore_errors: True
  become: yes
  become_method: sudo
  tags:
    - remove_java
  when: is_centos_os

- name: uninstall java
  file:
    path: "{{ JAVA_HOME }}"
    state: absent
  become: yes
  become_method: sudo
  tags:
    - remove_java
