---
- name: 切换默认终端为 bash
  ansible.builtin.command: "chsh -s /bin/bash {{ ansible_user_id }}"
  changed_when: true
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - remove_zsh

- name: 检查 .bash_profile 是否引用 /etc/bashrc
  ansible.builtin.shell: |
    set -o pipefail
    grep -c "if \[ \-f /etc/bashrc \]; then" "{{ common_home_root }}/.bash_profile" || true
  args:
    executable: /bin/bash
  register: uninstall_existing_of_etc_bashrc
  changed_when: false
  tags:
    - remove_zsh

- name: 输出 .bash_profile 引用 /etc/bashrc 检查结果
  ansible.builtin.debug:
    msg: ".bash_profile {{ '已引用 /etc/bashrc' if uninstall_existing_of_etc_bashrc.stdout != '0' else '未引用 /etc/bashrc' }}"
  tags:
    - remove_zsh

- name: 写入 /etc/bashrc 引用
  ansible.builtin.shell:
    cmd: |
      cat >>{{ common_home_root }}/.bash_profile<<EOF
      if [ -f /etc/bashrc ]; then
        . /etc/bashrc
      fi
      EOF
  changed_when: true
  when: uninstall_existing_of_etc_bashrc.stdout == "0"
  tags:
    - remove_zsh

- name: 在 RedHat 上卸载 zsh
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
    update_cache: true
  with_items:
    - zsh
  tags:
    - remove_zsh
  when: common_is_centos_os

- name: 在 Ubuntu 上卸载 zsh
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - zsh
  tags:
    - remove_zsh
  when: common_is_ubuntu_os

- name: 在 macOS 上卸载 zsh
  ansible.builtin.command: "brew uninstall {{ item }} --force"
  changed_when: true
  failed_when: false
  with_items:
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
  tags:
    - remove_zsh
  when: common_is_mac_os

- name: 删除 zsh 目录
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
    force: true
  with_items:
    - "{{ common_home_root }}/.zshrc"
    - "{{ common_home_root }}/.zshrc_history"
    - "{{ common_home_root }}/.zshrc.pre-oh-my-zsh"
    - "{{ common_home_root }}/.oh-my-zsh"
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - remove_zsh
