---

- name: change terminal
  shell: "chsh -s /bin/bash {{ ansible_user_id }}"
  become: true
  become_method: sudo
  tags:
    - remove_zsh

- name: check /etc/bahsrc exists
  shell: cat ~/.bash_profile | grep "if \[ \-f /etc/bashrc \]; then" | wc -l
  register: existing_of_etc_bashrc
  changed_when: False
  tags:
    - remove_zsh

- name: change bashrc
  shell:
    cmd: |
      cat >>{{ HOME_ROOT }}/.bash_profile<<EOF
      if [ -f /etc/bashrc ]; then
        . /etc/bashrc
      fi
      EOF
  when: existing_of_etc_bashrc.stdout == "0"
  tags:
    - remove_zsh

- name: uninstall zsh on Redhat
  yum:
    name: "{{ item }}"
    state: absent
    update_cache: true
  with_items:
    - zsh
  tags:
    - remove_zsh
  when: is_centos_os

- name: uninstall zsh on Ubuntu
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - zsh
  tags:
    - remove_zsh
  when: is_ubuntu_os

- name: uninstall zsh on macOS
  shell: "brew uninstall {{ item }} --force"
  ignore_errors: True
  with_items:
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
  tags:
    - remove_zsh
  when: is_mac_os

- name: remove zsh directory
  file:
    path: "{{ item }}"
    state: absent
    force: true
  with_items:
    - "{{ HOME_ROOT }}/.zshrc"
    - "{{ HOME_ROOT }}/.zshrc_history"
    - "{{ HOME_ROOT }}/.zshrc.pre-oh-my-zsh"
    - "{{ HOME_ROOT }}/.oh-my-zsh"
  become: true
  become_method: sudo
  tags:
    - remove_zsh
