apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit
  namespace: seekplum
spec:
  selector:
    matchLabels:
      app: gerrit
  replicas: 1
  template:
    metadata:
      labels:
        app: gerrit
    spec:
      volumes:
        - name: gerrit-volume-home
          hostPath:
            path: /root/data/develop/gerrit
            type: DirectoryOrCreate
      containers:
      - name: gerrit
        image: openfrontier/gerrit:3.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: gerrit
        ports:
          - name: http
            containerPort: 8080
          - name: ssh
            containerPort: 29418
        volumeMounts:
          - name: gerrit-volume-home
            mountPath: /var/gerrit/review_site
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 8
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: gerrit
  namespace: seekplum
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: ssh
    port: 29418
    protocol: TCP
    targetPort: 29418
  selector:
    app: gerrit
status:
  loadBalancer: {}
