apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: seekplum
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
        - name: jenkins-volume-home
          hostPath:
            path: /root/data/develop/jenkins
            type: DirectoryOrCreate
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: jenkins
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
          - name: jenkins-volume-home
            mountPath: /var/jenkins_home
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: seekplum
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
status:
  loadBalancer: {}
