apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldapadmin
  namespace: seekplum
spec:
  selector:
    matchLabels:
      app: ldapadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: ldapadmin
    spec:
      containers:
      - name: ldapadmin
        image: osixia/phpldapadmin:0.9.0
        imagePullPolicy: IfNotPresent
        args: ["--copy-service", "--loglevel=debug"]
        envFrom:
        - configMapRef:
            name: ldapadmin
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ldapadmin
  namespace: seekplum
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ldapadmin
status:
  loadBalancer: {}