apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: seekplum
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-volume-certificates
          hostPath:
            path: /root/PythonProjects/github.com/seekplum/deploy/roles/development/data/acme/.lego/certificates
        - name: nginx-volume-conf-d
          hostPath:
            path: /root/PythonProjects/github.com/seekplum/deploy/roles/development/conf/nginx/conf.d
        - name: nginx-volume-inc-d
          hostPath:
            path: /root/PythonProjects/github.com/seekplum/deploy/roles/development/conf/nginx/inc.d
        - name: nginx-volume-nginx-conf
          hostPath:
            path: /root/PythonProjects/github.com/seekplum/deploy/roles/development/conf/nginx/nginx.conf
        - name: nginx-volume-www
          hostPath:
            # path: /root/PythonProjects/github.com/seekplum/deploy/roles/development/data/www
            path: /root/PythonProjects/github.com/seekplum/deploy/roles/development/fe/dist/avatar-app
        - name: nginx-volume-logs
          hostPath:
            path: /root/data/develop/nginx/logs
            type: DirectoryOrCreate
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
          - name: nginx-volume-certificates
            mountPath: /etc/nginx/ssl
            readOnly: true
          - name: nginx-volume-conf-d
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: nginx-volume-inc-d
            mountPath: /etc/nginx/inc.d
            readOnly: true
          - name: nginx-volume-nginx-conf
            mountPath: /etc/nginx/nginx.conf
            readOnly: true
          - name: nginx-volume-www
            mountPath: /var/www
            readOnly: true
          - name: nginx-volume-logs
            mountPath: /var/log/nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: seekplum
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
status:
  loadBalancer: {}
