[program:copilot-api]
command=copilot-api start --proxy-env
directory=%(ENV_HOME)s
process_name=%(program_name)s
numprocs=1
redirect_stderr=true
stdout_logfile=%(ENV_HOME)s/packages/logs/%(program_name)s.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
stdout_capture_maxbytes=1MB
stdout_events_enabled=false
stopasgroup=true
autostart=false
autorestart=false
environment=
    PATH="%(ENV_PATH)s"
