[program:mitmproxy]
command=mitmdump -p 8123 -s proxy_rewrite.py --set upstream_cert=false --ssl-insecure
directory=%(ENV_HOME)s/packages/supervisor/conf.d
process_name=%(program_name)s
numprocs=1
redirect_stderr=true
stdout_logfile=%(ENV_HOME)s/packages/logs/%(program_name)s.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
stdout_capture_maxbytes=1MB
stdout_events_enabled=false
stopasgroup=true
autorestart=true
environment=
    PATH="%(ENV_HOME)s/packages/pythonenv/3.12.11/bin:%(ENV_PATH)s"
