version: "3"
services:
  ldap:
    image: osixia/openldap:1.3.0
    environment:
      LDAP_ORGANISATION: "seekplum.io"
      LDAP_DOMAIN: "seekplum.io"
      LDAP_ADMIN_PASSWORD: "seekplum"
      LDAP_CONFIG_PASSWORD: "seekplum"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "guest"
      LDAP_READONLY_USER_PASSWORD: "123456"
    volumes:
      - ${VOLUMES_ROOT}/slapd/database:/var/lib/ldap
      - ${VOLUMES_ROOT}/slapd/config:/etc/ldap/slapd.d
    restart: on-failure
    command:
      - --copy-service
      - --loglevel=debug
    networks:
      develop-network:
        aliases:
          - ldap-host
  ldapadmin:
    image: osixia/phpldapadmin:0.9.0
    depends_on:
      - ldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-host"
      PHPLDAPADMIN_HTTPS: "false"
    restart: on-failure
    networks:
      develop-network:
        aliases:
          - ldapadmin-host
  gerrit:
    image: openfrontier/gerrit
    depends_on:
      - ldap
    volumes:
      - ${VOLUMES_ROOT}/gerrit:/var/gerrit/review_site
    environment:
      WEBURL: http://gerrit.seekplum.com
      GITWEB_TYPE: gitiles
      AUTH_TYPE: LDAP
      LDAP_SERVER: ldap://ldap-host
      LDAP_ACCOUNTBASE: dc=seekplum,dc=io
      LDAP_ACCOUNTPATTERN: (cn=$${username})
      LDAP_ACCOUNTSSHUSERNAME: $${cn}
      LDAP_ACCOUNTFULLNAME: $${sn}
      LDAP_USERNAME: cn=guest,dc=seekplum,dc=io
      LDAP_PASSWORD: 123456
      GERRIT_INIT_ARGS: --install-plugin=download-commands
    restart: on-failure
    healthcheck:
      test: "if [ `curl -I -m 10 -o /dev/null -s -w %{http_code} http://gerrit-host:8080` -ne 200 ]; then exit 1; else exit 0; fi;"
      interval: 5s
      timeout: 1s
      retries: 14
    networks:
      develop-network:
        aliases:
          - gerrit-host
  nginx:
    image: nginx:alpine
#    network_mode: host  # MacOSX不支持host模式
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./conf/nginx/inc.d:/etc/nginx/inc.d:ro
      - ./data/www:/var/www:ro
      - ${VOLUMES_ROOT}/nginx/logs:/var/log/nginx
    restart: always
    networks:
      - develop-network

networks:
  develop-network:
    driver: bridge
