---
- name: 检查 k3s server 卸载脚本是否存在
  ansible.builtin.stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: k3s_server_scripts
  tags:
    - remove_k3s_scripts
  when: common_is_linux_os

- name: 输出 k3s server 卸载脚本检查结果
  ansible.builtin.debug:
    msg: "k3s server 卸载脚本 {{ '已存在' if k3s_server_scripts.stat.exists else '不存在' }}"
  tags:
    - remove_k3s_scripts
  when: common_is_linux_os

- name: 检查 k3s agent 卸载脚本是否存在
  ansible.builtin.stat:
    path: /usr/local/bin/k3s-agent-uninstall.sh
  register: k3s_agent_scripts
  tags:
    - remove_k3s_scripts
  when: common_is_linux_os

- name: 输出 k3s agent 卸载脚本检查结果
  ansible.builtin.debug:
    msg: "k3s agent 卸载脚本 {{ '已存在' if k3s_agent_scripts.stat.exists else '不存在' }}"
  tags:
    - remove_k3s_scripts
  when: common_is_linux_os

- name: 卸载 k3s server
  ansible.builtin.command: "sh /usr/local/bin/k3s-uninstall.sh"
  changed_when: false
  failed_when: false
  tags:
    - remove_k3s_scripts
  become: true
  become_method: ansible.builtin.sudo
  when: common_is_linux_os and k3s_server_scripts.stat.exists

- name: 卸载 k3s agent
  ansible.builtin.command: "sh /usr/local/bin/k3s-agent-uninstall.sh"
  changed_when: false
  failed_when: false
  tags:
    - remove_k3s_scripts
  become: true
  become_method: ansible.builtin.sudo
  when: common_is_linux_os and k3s_agent_scripts.stat.exists

- name: 在 RedHat 上卸载 k3s-selinux
  ansible.builtin.dnf:
    name: k3s-selinux
    state: absent
    autoremove: true
  tags:
    - remove_k3s_packages
  failed_when: false
  when: common_is_centos_os

- name: 在 RedHat 上卸载 k3s
  ansible.builtin.dnf:
    name: "k3s*"
    state: absent
    autoremove: true
  tags:
    - remove_k3s_packages
  failed_when: false
  when: common_is_centos_os

- name: "删除文件"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
    force: true
  with_items:
    - "{{ common_home_root }}/.kube/"
    - "/etc/rancher"
    - "/var/lib/rancher"
    - "/usr/local/bin/k3s-killall.sh"
    - "/usr/local/bin/k3s"
    - "/usr/local/bin/kubectl"
    - "/usr/local/bin/ctr"
    - "/usr/local/bin/crictl"
  tags:
    - remove_k3s_files
  become: true
  become_method: ansible.builtin.sudo
  when: common_is_linux_os

- name: "删除 stern"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
    force: true
  with_items:
    - "/tmp/stern"
    - "/usr/local/bin/remove_stern"
  tags:
    - remove_stern
  become: true
  become_method: ansible.builtin.sudo
  when: common_is_linux_os

- name: "删除 helm"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
    force: true
  with_items:
    - "{{ common_home_root }}/linux-amd64"
    - "/usr/local/bin/helm"
  tags:
    - remove_helm
  become: true
  become_method: ansible.builtin.sudo
  when: common_is_linux_os
