---
- name: 复制 k3s agent 配置文件
  ansible.builtin.copy:
    src: "agent-config.yaml"
    dest: "/etc/rancher/k3s/config.yaml"
    mode: "0644"
    force: true
  tags:
    - k3s_agent
  become: true
  become_method: ansible.builtin.sudo
  when: common_is_linux_os

- name: "获取 k3s server token"
  ansible.builtin.shell: |
    set -o pipefail
    awk -F ':' '{print $4}' /var/lib/rancher/k3s/server/node-token
  args:
    executable: /bin/bash
  register: k3s_server_token
  changed_when: false
  tags:
    - k3s_agent
  when: common_is_linux_os and common_is_master_node

- name: "输出 k3s token"
  ansible.builtin.debug:
    var: k3s_server_token.stdout
  tags:
    - k3s_agent
  when: common_is_linux_os and common_is_master_node and k3s_server_token is defined and "stdout" in k3s_server_token

- name: "设置 token 变量"
  ansible.builtin.set_fact:
    k3s_server_token: "{{ k3s_server_token.stdout }}"
  tags:
    - k3s_agent
  when: common_is_linux_os and common_is_master_node and "stdout" in k3s_server_token

- name: "设置 k3s_url 变量"
  ansible.builtin.set_fact:
    k3s_server_url: "https://{{ K3S_SERVER_IP | default(ansible_default_ipv4.address) }}:6443"
  tags:
    - k3s_agent
  when: common_is_linux_os and common_is_master_node

- name: "设置加入节点命令"
  ansible.builtin.set_fact:
    k3s_join_cmd: 'curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_VERSION={{ INSTALL_K3S_VERSION | default("") }} INSTALL_K3S_MIRROR=cn
      K3S_TOKEN={{ hostvars[groups["masters"][0]]["k3s_server_token"] }} K3S_URL={{ hostvars[groups["masters"][0]]["k3s_server_url"] }} INSTALL_K3S_EXEC="--token
      ${K3S_TOKEN} --server ${K3S_URL} --docker" sh -s -'
  tags:
    - k3s_agent
  when: common_is_linux_os and common_is_slaves_node and "k3s_server_token" in hostvars[groups["masters"][0]] and
    hostvars[groups['masters'][0]]['k3s_server_token'] != ""

- name: "输出加入节点命令"
  ansible.builtin.debug:
    msg: "{{ k3s_join_cmd }}"
  tags:
    - k3s_agent
  when: common_is_linux_os and common_is_slaves_node and k3s_join_cmd is defined

- name: 在 Linux 上安装 k3s agent
  ansible.builtin.shell: |
    set -o pipefail
    {{ k3s_join_cmd }}
  args:
    executable: /bin/bash
  register: k3s_agent_install_result
  changed_when: true
  tags:
    - k3s_agent
  become: true
  become_method: ansible.builtin.sudo
  when: common_is_linux_os and common_is_slaves_node and k3s_join_cmd is defined

- name: "输出安装信息"
  ansible.builtin.debug:
    msg: "{{ k3s_agent_install_result }}"
  tags:
    - k3s_agent
  when: common_is_linux_os and common_is_slaves_node

- name: 在 Linux 上启动 k3s agent
  ansible.builtin.service:
    name: "k3s-agent"
    state: "started"
    enabled: "yes"
  register: k3s_service_result
  failed_when: false
  tags:
    - k3s_agent
  when: common_is_linux_os and common_is_slaves_node
