---
# tasks file for k3s

- name: 执行 k3s 卸载任务
  ansible.builtin.import_tasks: k3s_uninstall.yml
  tags:
    - remove_k3s

- name: 执行 k3s 安装任务
  ansible.builtin.import_tasks: k3s_install.yml
  tags:
    - k3s_install

- name: 执行 k3s 节点加入任务
  ansible.builtin.import_tasks: k3s_join.yml
  tags:
    - k3s_join
