---
- name: "清除hosts配置"
  shell: 'sed -i "/^{{ item }}.*/d" /etc/hosts'
  with_items:
    - '{{groups["masters"][0]}}'
    - '{{groups["slaves"][0]}}'
    - '{{groups["slaves"][1]}}'
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "配置hosts"
  shell: 'echo {{item}} {{ hostvars[item].ansible_hostname }} >> /etc/hosts'
  with_items:
    - '{{groups["masters"][0]}}'
    - '{{groups["slaves"][0]}}'
    - '{{groups["slaves"][1]}}'
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "关闭防火墙"
  shell: 'ufw disable'
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "修改docker启动配置"
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
    force: true
    backup: true # 进行备份
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "临时关闭交换分区"
  shell: "{{item}}"
  with_items:
    - swapoff -a
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "获取交换分区名字"
  shell: cat /etc/fstab | grep " swap " | awk '{print $1}'
  register: swap_name
  changed_when: False
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "永久关闭交换分区"
  shell: sed -i "s#^{{ swap_name.stdout }}#\#&#g" /etc/fstab
  tags:
    - kubeadm
  when: ansible_os_family == "Debian" and not swap_name.stdout.startswith("#")


- name: "添加阿里源"
  shell: "curl -s https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg | apt-key add -"
  changed_when: False
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "修改k8s源内容"
  shell:
    cmd: |
      tee /etc/apt/sources.list.d/kubernetes.list <<EOF
      deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main
      EOF
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "安装kubeadm"
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - kubelet
    - kubectl
    - kubeadm
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "获取kubeadm版本"
  shell: kubeadm version | grep -E -o 'GitVersion:"(v[0-9\.]+)"' | grep -E -o '(v[0-9\.]+)'
  register: kubeadm_version
  changed_when: False
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "生成配置文件"
  shell: "kubeadm config print init-defaults ClusterConfiguration > {{KUBEADM_CONFIG_PATH}}"
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "修改配置文件"
  shell: "{{item}}"
  with_items:
    - 'sed -i "s#^imageRepository.*#imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers#g" {{KUBEADM_CONFIG_PATH}}'
    - 'sed -i "s#^kubernetesVersion.*#kubernetesVersion: {{ kubeadm_version.stdout }}#g" {{KUBEADM_CONFIG_PATH}}'
    - 'sed -i "s#advertiseAddress.*#advertiseAddress: {{ ansible_default_ipv4.address }}#g" {{KUBEADM_CONFIG_PATH}}'
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "重启Docker"
  shell: systemctl daemon-reload && systemctl restart docker
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "重启kubelet"
  shell: systemctl daemon-reload && systemctl enable kubelet && systemctl restart kubelet
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "修改kubelet cgroup类型"
  shell: 'sed -i "s/--cgroup-driver=[a-zA-Z]*/--cgroup-driver=systemd/g" /var/lib/kubelet/kubeadm-flags.env'
  ignore_errors: True
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "拉取镜像"
  shell: "kubeadm config images pull --config {{KUBEADM_CONFIG_PATH}}"
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "删除重复的文件"
  file:
    path: "{{item}}"
    state: absent
    force: true
  with_items:
    - "/etc/kubernetes/manifests/kube-apiserver.yaml"
    - "/etc/kubernetes/manifests/kube-controller-manager.yaml"
    - "/etc/kubernetes/manifests/kube-scheduler.yaml"
    - "/etc/kubernetes/manifests/etcd.yaml"
  tags:
    - kubeadm
  when: ansible_os_family == "Debian" and ansible_default_ipv4.address in groups['masters']

- name: "Master修改server"
  shell: 'sed -i "s#server: https://.*:6443#server: https://{{ansible_default_ipv4.address}}:6443#g" {{item}}'
  ignore_errors: True
  with_items:
    - '/etc/kubernetes/kubelet.conf'
    - '/etc/kubernetes/controller-manager.conf'
    - '/etc/kubernetes/scheduler.conf'
  tags:
    - kubeadm
  when: ansible_os_family == "Debian" and ansible_default_ipv4.address in groups['masters']

- name: "检查CNI插件是否已经下载"
  shell: "test -f {{CNI_PLUGINS_PATH_ON_LINUX}} && echo 0 || echo 1"
  register: existing_of_cni_plugins
  changed_when: False
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "安装CNI插件"
  block:
    - name: "创建目录"
      shell: "mkdir -p {{CNI_PLUGINS_DIRECTOR_ON_LINUX}}"

    - name: "下载CNI插件"
      get_url:
        url: "{{CNI_PLUGINS_URL_ON_LINUX}}"
        dest: "{{CNI_PLUGINS_PATH_ON_LINUX}}"
        force: false
      when: existing_of_cni_plugins.stdout == "1"

    - name: "解压CNI插件"
      unarchive:
        src: "{{CNI_PLUGINS_PATH_ON_LINUX}}"
        dest: "{{CNI_PLUGINS_DIRECTOR_ON_LINUX}}"
        remote_src: true
  tags:
    - kubeadm
  when: ansible_os_family == "Debian"

- name: "Master初始化"
  shell: "{{item}}"
  register: kubeadm_init
  with_items:
    - "netstat -alnp | grep -E ':6443 |:10251 |:10252 |:10250 ' | awk '{print $7}' | cut -d'/' -f1 | grep -v '-' | xargs kill -9"
    - "kubeadm init --config {{KUBEADM_CONFIG_PATH}} --ignore-preflight-errors=Swap"
  ignore_errors: True
  tags:
    - kubeadm
  when: ansible_os_family == "Debian" and ansible_default_ipv4.address in groups['masters']

- name: "输出初始化信息"
  debug: msg={{ kubeadm_init }}
  tags:
    - kubeadm
  when: ansible_os_family == "Debian" and ansible_default_ipv4.address in groups['masters']

- name: "Master初始化后操作"
  shell: "{{item}}"
  with_items:
    - "mkdir -p $HOME/.kube"
    - "scp /etc/kubernetes/admin.conf $HOME/.kube/config"
    - "chown $(id -u):$(id -g) $HOME/.kube/config"
  tags:
    - kubeadm
  when: ansible_os_family == "Debian" and ansible_default_ipv4.address in groups['masters']

- name: "Master安装Pod网络"
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  tags:
    - kubeadm
  when: ansible_os_family == "Debian" and ansible_default_ipv4.address in groups['masters']
