---
- name: "重置集群"
  ansible.builtin.command: kubeadm reset -f
  changed_when: false
  failed_when: false
  tags:
    - join_kubeadm
  when: common_is_linux_os

- name: "初始化 Master 节点"
  ansible.builtin.shell: |
    set -o pipefail
    {{ item }}
  args:
    executable: /bin/bash
  register: kubernetes_kubeadm_init
  with_items:
    - "netstat -alnp | grep -E ':6443 |:10251 |:10252 |:10250 ' | awk '{print $7}' | cut -d'/' -f1 | grep -v '-' | xargs kill -9 >/dev/null 2&> 1"
    - "kubeadm init --ignore-preflight-errors=Cri --cri-socket={{ kubernetes_cri_socket }}"
  changed_when: true
  failed_when: false
  tags:
    - join_kubeadm
  when: common_is_master_node

- name: 输出初始化信息
  ansible.builtin.debug:
    msg: "{{ kubernetes_kubeadm_init }}"
  tags:
    - join_kubeadm
  when: common_is_master_node

- name: 检查 Master 初始化是否成功
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_admin_conf_stat
  changed_when: false
  tags:
    - join_kubeadm
  when: common_is_master_node

- name: 输出 Master 初始化检查结果
  ansible.builtin.debug:
    msg: "Master 初始化 {{ '成功' if kubernetes_admin_conf_stat.stat.exists else '失败，请检查日志' }}"
  tags:
    - join_kubeadm
  when: common_is_master_node

- name: "执行 Master 初始化后操作"
  ansible.builtin.shell: |
    mkdir -p "$HOME/.kube"
    cp /etc/kubernetes/admin.conf "$HOME/.kube/config"
    chown "$(id -u):$(id -g)" "$HOME/.kube/config"
  changed_when: true
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists

- name: "部署 Calico CNI 网络插件"
  ansible.builtin.shell: |
    set -o pipefail
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml
  args:
    executable: /bin/bash
  register: kubernetes_calico_install
  changed_when: true
  failed_when: false
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists

- name: "查询coredns角色配置"
  ansible.builtin.command: "kubectl get clusterrole system:coredns -o yaml"
  register: kubernetes_coredns_configured
  changed_when: false
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists

- name: "设置更新后内容"
  ansible.builtin.set_fact:
    kubernetes_coredns_yml_output: "{{ kubernetes_coredns_configured.stdout + '\n- apiGroups:\n  - discovery.k8s.io\n  resources:\n  - endpointslices\n  verbs:\n  - list\n\
      \  - watch' }}"
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists and "stdout" in kubernetes_coredns_configured

- name: "输出coredns配置"
  ansible.builtin.debug:
    msg: "{{ kubernetes_coredns_yml_output }}"
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists and kubernetes_coredns_yml_output is defined

- name: "修复coredns角色异常"
  # https://github.com/coredns/helm/issues/9
  ansible.builtin.shell: |
    set -o pipefail
    printf '%s\n' "{{ kubernetes_coredns_yml_output }}" | sed '/resourceVersion:/d' | kubectl apply -f -
  args:
    executable: /bin/bash
  changed_when: true
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists and kubernetes_coredns_yml_output is defined

- name: "修复组件健康状态异常"
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: "(- --port=0)"
    replace: "# \\1"
  with_items:
    - /etc/kubernetes/manifests/kube-scheduler.yaml
    - /etc/kubernetes/manifests/kube-controller-manager.yaml
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists

- name: "重启kubelet"
  ansible.builtin.service:
    name: "kubelet"
    state: "restarted"
    enabled: "yes"
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists

- name: "获取kubeadm token"
  ansible.builtin.shell: |
    set -o pipefail
    kubeadm token list | awk '{if(NR>1)print}' | head -n 1 | awk '{print $1}'
  args:
    executable: /bin/bash
  register: kubernetes_get_kubeadm_token
  changed_when: false
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists

- name: "设置 token 变量"
  ansible.builtin.set_fact:
    kubernetes_kubeadm_token: "{{ kubernetes_get_kubeadm_token.stdout }}"
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists and "stdout" in kubernetes_get_kubeadm_token

- name: "生成kubeadm token"
  ansible.builtin.command: kubeadm token create
  register: kubernetes_create_kubeadm_token
  changed_when: false
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists and kubernetes_kubeadm_token is defined and kubernetes_kubeadm_token == ""

- name: "设置重新生成的 token 变量"
  ansible.builtin.set_fact:
    kubernetes_kubeadm_token: "{{ kubernetes_create_kubeadm_token.stdout }}"
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists and kubernetes_kubeadm_token is defined and kubernetes_kubeadm_token == ""

- name: "输出token"
  ansible.builtin.debug:
    var: kubernetes_kubeadm_token
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists and kubernetes_kubeadm_token is defined

- name: "生成kubeadm join命令"
  ansible.builtin.command: "echo kubeadm join --token={{ kubernetes_kubeadm_token }} {{ hostvars[groups['masters'][0]].ansible_default_ipv4.address }}:6443 --discovery-token-unsafe-skip-ca-verification"
  register: kubernetes_kubeadm_join_token
  changed_when: false
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists and kubernetes_kubeadm_token is defined

- name: "输出join命令"
  ansible.builtin.debug:
    var: kubernetes_kubeadm_join_token.stdout
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists and kubernetes_kubeadm_join_token is defined and "results" in kubernetes_kubeadm_join_token and "stdout" in
    kubernetes_kubeadm_join_token

- name: "设置加入节点命令"
  ansible.builtin.set_fact:
    kubernetes_kubeadm_join_token_cmd: "{{ kubernetes_kubeadm_join_token.stdout }}"
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists and "stdout" in kubernetes_kubeadm_join_token

- name: "将 Slave 节点加入 Kubernetes"
  ansible.builtin.command: '{{ hostvars[groups["masters"][0]]["kubernetes_kubeadm_join_token_cmd"] }}'
  register: kubernetes_slave_kubeadm_join_result
  changed_when: true
  tags:
    - join_kubeadm
  when: common_is_slaves_node and kubernetes_admin_conf_stat.stat.exists and "kubernetes_kubeadm_join_token_cmd" in hostvars[groups["masters"][0]] and
    hostvars[groups["masters"][0]]["kubernetes_kubeadm_join_token_cmd"] != ""

- name: "输出slave join结果"
  ansible.builtin.debug:
    var: kubernetes_slave_kubeadm_join_result.stdout
  tags:
    - join_kubeadm
  when: common_is_slaves_node and kubernetes_admin_conf_stat.stat.exists

- name: "查询节点、Pod状态"
  ansible.builtin.command: "{{ item }}"
  register: kubernetes_kubeadm_pods_info
  changed_when: false
  with_items:
    - kubectl get nodes,cs -o wide
    - kubectl --namespace kube-system get pods -o wide
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists

- name: "输出Pod信息"
  ansible.builtin.debug:
    msg: "{{ kubernetes_kubeadm_pods_info }}"
  tags:
    - join_kubeadm
  when: common_is_master_node and kubernetes_admin_conf_stat.stat.exists
