---
# tasks file for kubernetes

- name: 执行 kubeadm 卸载任务
  ansible.builtin.import_tasks: kubeadm_uninstall.yml
  tags:
    - remove_kubeadm

- name: 执行 kubeadm 安装任务
  ansible.builtin.import_tasks: kubeadm_install.yml
  tags:
    - kubeadm

- name: 执行 kubeadm 节点加入任务
  ansible.builtin.import_tasks: kubeadm_join.yml
  tags:
    - join_kubeadm
