---
# tasks file for kubernetes

- name: 执行 kubeadm 卸载任务
  ansible.builtin.include_tasks: kubeadm_uninstall.yml

- name: 执行 kubeadm 安装任务
  ansible.builtin.include_tasks: kubeadm_install.yml

- name: 执行 kubeadm 节点加入任务
  ansible.builtin.include_tasks: kubeadm_join.yml
