#!/bin/sh
#
# /etc/rc.d/init.d/supervisord
#
# Supervisor is a client/server system that
# allows its users to monitor and control a
# number of processes on UNIX-like operating
# systems.
#
# chkconfig: - 64 36
# description: Supervisor Server
# processname: supervisord
# Source init functions
. /etc/rc.d/init.d/functions
prog="supervisord"
prefix="/home/hjd/hjd-dev-env"
exec_prefix="${prefix}"
prog_bin="${exec_prefix}/bin/supervisord"
conf=/home/hjd/hjd-dev-env/packages/conf/supervisor/supervisord.conf
prog_stop_bin="${exec_prefix}/bin/supervisorctl"
PIDFILE="/tmp/hjd_supervisord.pid"
start()
{
       echo -n $"Starting $prog: "
       daemon $prog_bin --pidfile $PIDFILE -c $conf
       [ -f $PIDFILE ] && success $"$prog startup" || failure $"$prog startup"
       echo
}
stop()
{
       [ -f $PIDFILE ] && action "Stopping $prog"  $prog_stop_bin -c $conf shutdown || success $"$prog shutdown"
       echo
}
case "$1" in
 start)
   start
 ;;
 stop)
   stop
 ;;
 status)
       status $prog
 ;;
 restart)
   stop
   start
 ;;
 *)
   echo "Usage: $0 {start|stop|restart|status}"
 ;;
esac

