---
# vars file for install

GOPATH: "{{ HOME_ROOT }}/GolangProjects"
WebProjects: "{{ HOME_ROOT }}/WebProjects"
PythonProjects: "{{ HOME_ROOT }}/PythonProjects"
JavaProjects: "{{ HOME_ROOT }}/JavaProjects"
GO_PACKAGE_PATH_ON_LINUX: "{{ HOME_ROOT }}/go{{ GO_VERSION }}.linux-amd64.tar.gz"
GO_PACKAGE_PATH_ON_MAC: "{{ HOME_ROOT }}/go{{ GO_VERSION }}.darwin-amd64.tar.gz"
JAVA_PACKAGE_PATH_ON_LINUX: "{{ HOME_ROOT }}/jdk-8u351-linux-x64.tar.gz"
MVN_PACKAGE_PATH_ON_LINUX: "{{ HOME_ROOT }}/apache-maven-3.8.6-bin.tar.gz"
HELM_VERSION: "v3.7.1"
HELM_PACKAGE_PATH_ON_LINUX: "{{ HOME_ROOT }}/helm-{{ HELM_VERSION }}-linux-amd64.tar.gz"
GO_DOWNLOAD_URL_ON_MAC: "https://golang.org/dl/go{{ GO_VERSION }}.darwin-amd64.tar.gz"
GO_DOWNLOAD_URL_ON_LINUX: "https://golang.org/dl/go{{ GO_VERSION }}.linux-amd64.tar.gz"
# https://www.oracle.com/java/technologies/downloads/#java8
# 需要登录Oracle才能下载
JAVA_DOWNLOAD_URL_ON_LINUX: "https://download.oracle.com/otn/java/jdk/8u351-b10/10e8cce67c7843478f41411b7003171c/jdk-8u351-linux-x64.tar.gz"
MVN_DOWNLOAD_URL_ON_LINUX: "https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz"
HELM_DOWNLOAD_URL_ON_LINUX: "https://get.helm.sh/helm-{{ HELM_VERSION }}-linux-amd64.tar.gz"
STERN_VERSION: "1.11.0"
STERN_DOWNLOAD_URL_ON_LINUX: "https://github.com/wercker/stern/releases/download/{{ STERN_VERSION }}/stern_linux_amd64"
PYCONCREATE_VERSION: "v0.15.1"
PYCONCREATE_PATH: "{{ HOME_ROOT }}/pyconcrete-{{ PYCONCREATE_VERSION }}.tar.gz"
PYCONCREATE_DIRECTORY: "{{ HOME_ROOT }}/pyconcrete-{{ PYCONCREATE_VERSION[1:] }}"
PACKAGES_ROOT: "{{ HOME_ROOT }}/packages"
NODE_VERSION: "v14.18.2"
PYENV_ROOT: "{{ HOME_ROOT }}/.pyenv"
PYENV_REPOSITORY: "git@github.com:pyenv/pyenv.git"
RBENV_ROOT: "{{ HOME_ROOT }}/.rbenv"
RBENV_REPOSITORY: "git@github.com:rbenv/rbenv.git"
RUBY_BUILD_ROOT: "{{ RBENV_ROOT }}/plugins/ruby-build"
RUBY_BUILD_REPOSITORY: "git@github.com:rbenv/ruby-build.git"
VIRTUEL_ROOT: "{{ PACKAGES_ROOT }}/pythonenv"
PY_PIP_PATH: "{{ HOME_ROOT }}/get-pip.py"
VIRTUAL_ENVS:
  - version: "{{ PYTHON2_VERSION }}"
  - version: "{{ PYTHON3_VERSION }}"
