---
- name: check existing python
  shell: "test -f {{VIRTUEL_ROOT}}/{{item.directory}}/{{item.name}}/bin/{{item.python}} && echo 0 || echo 1"
  register: existing_of_python
  changed_when: False

- name: check existing env pip
  shell: "test -f {{VIRTUEL_ROOT}}/{{item.directory}}/bin/{{item.pip}} && echo 0 || echo 1"
  register: existing_of_env_pip
  changed_when: False

- name: unarchive python
  shell: "tar -zxvf {{item.path}} -C {{TEMP_ROOT}}/Python-{{item.version}} --strip-components=1"
  register: result_unarchive_python
  when: existing_of_python.stdout == "1"

- name: compile and install python
  shell: "./configure --prefix={{VIRTUEL_ROOT}}/{{item.directory}}/{{item.name}} --with-ssl --with-zlib \
    --enable-loadable-sqlite-extensions --enable-optimizations && make && make install"
  args:
    chdir: "{{TEMP_ROOT}}/Python-{{item.version}}"
  register: result_of_compile_python
  ignore_errors: True
  when: existing_of_python.stdout == "1"

- name: install pip virtualenv
  command: "{{VIRTUEL_ROOT}}/{{item.directory}}/{{item.name}}/bin/{{item.python}} get-pip.py"
  args:
    chdir: "{{TEMP_ROOT}}"
  register: result_of_install pip
  when: existing_of_python.stdout == "1" and existing_of_env_pip == "1"
