---
- name: 检查虚拟环境是否已存在
  ansible.builtin.stat:
    path: "{{ install_virtual_root }}/{{ env_item.version }}/bin/python"
  register: install_virtualenv_python_stat
  loop: "{{ install_virtual_envs }}"
  loop_control:
    loop_var: env_item
  tags:
    - virtualenv

- name: 输出虚拟环境检查结果
  ansible.builtin.debug:
    msg: "{{ item.env_item.version }} 虚拟环境 {{ '已存在' if item.stat.exists else '不存在' }}"
  loop: "{{ install_virtualenv_python_stat.results }}"
  tags:
    - virtualenv

- name: 创建虚拟环境
  ansible.builtin.command:
    cmd: >-
      uv venv {{ install_virtual_root }}/{{ env_item.version }}
      --prompt {{ env_item.version }}
      --python {{ env_item.version }}
    creates: "{{ install_virtual_root }}/{{ env_item.version }}/bin/python"
  loop: "{{ install_virtual_envs }}"
  loop_control:
    loop_var: env_item
  tags:
    - virtualenv

- name: 复制 requirements.in
  ansible.builtin.copy:
    src: "requirements.in"
    dest: "/tmp/requirements.in"
    mode: "0644"
    force: true
    backup: false
  tags:
    - virtualenv

- name: 检查虚拟环境依赖包是否已安装
  ansible.builtin.stat:
    path: "{{ install_virtual_root }}/{{ env_item.version }}/.requirements_installed"
  register: install_virtualenv_packages_stat
  loop: "{{ install_virtual_envs }}"
  loop_control:
    loop_var: env_item
  tags:
    - virtualenv
  when: env_item.version.startswith("3.")

- name: 输出虚拟环境依赖包检查结果
  ansible.builtin.debug:
    msg: "{{ item.env_item.version }} 虚拟环境依赖包 {{ '已安装' if item.stat.exists else '未安装' }}"
  loop: "{{ install_virtualenv_packages_stat.results }}"
  tags:
    - virtualenv
  when: item.stat is defined

- name: 安装虚拟环境依赖包
  ansible.builtin.shell: |
    set -o pipefail
    uv pip install \
      --python "{{ install_virtual_root }}/{{ item.env_item.version }}/bin/python" \
      -r /tmp/requirements.in
    touch "{{ install_virtual_root }}/{{ item.env_item.version }}/.requirements_installed"
  args:
    executable: /bin/bash
  changed_when: true
  loop: "{{ install_virtualenv_packages_stat.results }}"
  tags:
    - virtualenv
  when:
    - item.stat is defined
    - not item.stat.exists
