---
- name: make virtualenv
  shell: "{{ PYENV_ROOT }}/versions/{{ item.version }}/bin/virtualenv --python={{ PYENV_ROOT }}/versions/{{ item.version }}/bin/python {{ VIRTUEL_ROOT }}/{{ item.version }}"
  tags:
    - virtualenv

- name: copy requirements.in
  copy:
    src: "requirements.in"
    dest: "/tmp/requirements.in"
    mode: 644
    force: true
    backup: false
  tags:
    - virtualenv

- name: install packages
  shell: "[[ ! -f {{ VIRTUEL_ROOT }}/{{ item.version }}/bin/trash ]] && {{ VIRTUEL_ROOT }}/{{ item.version }}/bin/pip install -r /tmp/requirements.in"
  with_items: "{{ VIRTUAL_ENVS }}"
  ignore_errors: True
  tags:
    - virtualenv
  when: item.version.startswith("3.")
