---
- name: make virtualenv
  shell: "[[ ! -d {{ VIRTUEL_ROOT }}/{{ env_item.version }} ]] && uv venv {{ VIRTUEL_ROOT }}/{{ env_item.version }} --prompt {{ env_item.version }} --python {{ env_item.version }} || echo {{ env_item.version }} virtualenv is exist"
  tags:
    - virtualenv

- name: copy requirements.in
  copy:
    src: "requirements.in"
    dest: "/tmp/requirements.in"
    mode: "0644"
    force: true
    backup: false
  tags:
    - virtualenv

- name: install packages
  shell: "[[ ! -f {{ VIRTUEL_ROOT }}/{{ env_item.version }}/bin/trash ]] && uv pip install --python {{ VIRTUEL_ROOT }}/{{ env_item.version }}/bin/python -r /tmp/requirements.in || echo {{ env_item.version }} virtualenv packages is exist"
  with_items: "{{ VIRTUAL_ENVS }}"
  ignore_errors: true
  tags:
    - virtualenv
  when: env_item.version.startswith("3.")
