---
- name: check existing of env
  shell: "test -f {{VIRTUEL_ROOT}}/{{item.directory}}/{{item.name}}/bin/activate && echo 0 || echo 1"
  register: result_of_check_env
  changed_when: false

- name: check existing of pyconcrete of env
  shell: "test -f {{VIRTUEL_ROOT}}/{{item.directory}}/{{item.name}}/bin/pyconcrete-admin.py && echo 0 || echo 1"
  register: result_of_check_pyconcrete
  changed_when: false

- name: make virtualenv
  shell:
    "virtualenv --always-copy --python={{VIRTUEL_ROOT}}/{{item.directory}}/{{item.name}}/bin/{{item.python}} \
    {{VIRTUEL_ROOT}}/{{item.directory}}"
  when: result_of_check_env.stdout == "1"
  register: result_of_make_env

- name: install pyconcrete into virtualenv
  shell:
    ". {{VIRTUEL_ROOT}}/{{item.directory}}/bin/activate && \
    {{item.python}} setup.py install --passphrase=$PASSPHRASE"
  args:
    chdir: "{{TEMP_ROOT}}/pyconcrete-0.10.2"
  when: result_of_unarchive_pyconcrete.changed or result_of_check_pyconcrete.stdout == "1"
  register: result_of_install_pyconcrete
