---
- name: make virtualenv
  shell: "{{ PYENV_ROOT }}/versions/{{ item.version }}/bin/virtualenv --python={{ PYENV_ROOT }}/versions/{{ item.version }}/bin/python {{ VIRTUEL_ROOT }}/{{ item.version }}"
  tags:
    - virtualenv
