---
# tasks file for install

# 1. 需要配置 sudo 免密 vi /etc/sudoers
# seekplum        ALL=(ALL) NOPASSWD: ALL
# %sudo   ALL=(ALL) NOPASSWD: ALL
# 2. macOS 需要先安装基础软件才能登陆 xcode-select --install

- name: 创建项目目录
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ common_home_root }}/.ssh"
    - "{{ common_home_root }}/.pip"
    - "/usr/local/bin"
    # - "{{ install_gopath }}"
    # - "{{ install_python_projects }}"
    # - "{{ install_web_projects }}"
    # - "{{ install_java_projects }}"
    - "{{ common_packages_root }}"
  tags:
    - configure_project_dirs

- name: 在 macOS 上链接 VirtualBox 脚本到 PATH
  ansible.builtin.file:
    src: "{{ common_packages_root }}/{{ item }}"
    dest: "/usr/local/bin/{{ item.replace('.sh', '') }}"
    state: link
    force: false # 避免原主机文件被覆盖
  with_items:
    - "start_vm.sh"
    - "stop_vm.sh"
    - "replace_config.sh"
  tags:
    - configure_virtualbox_scripts
  become: true
  become_method: ansible.builtin.sudo
  failed_when: false
  when: common_is_mac_os

- name: 在 Ubuntu 上导入 GPG 密钥
  ansible.builtin.shell: |
    set -o pipefail
    wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  args:
    executable: /bin/bash
  changed_when: false
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - configure_ubuntu_sources
  when: common_is_ubuntu_os

- name: 在 Ubuntu 上复制 apt 源列表
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/apt/"
    mode: "0644"
    force: true
  become: true
  become_method: ansible.builtin.sudo
  with_items:
    - "sources.list"
  tags:
    - configure_ubuntu_sources
  when: common_is_ubuntu_os

- name: 在 Ubuntu 上复制 Git PPA 源列表
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/apt/sources.list.d/"
    mode: "0644"
    force: true
  become: true
  become_method: ansible.builtin.sudo
  with_items:
    - "mongodb-org.list"
    - "git-core-ubuntu-ppa-focal.list"
  tags:
    - configure_ubuntu_sources
  when: common_is_ubuntu_os

- name: 在 Redhat 上备份软件源配置
  ansible.builtin.copy:
    src: "/etc/yum.repos.d/{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}.{{ install_backup_date }}.{{ install_backup_epoch }}"
    remote_src: true
    mode: preserve
  with_items:
    - "wandisco-git.repo"
    - "mongodb.repo"
  changed_when: false
  failed_when: false
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - configure_redhat_sources
  when: common_is_centos_os

- name: 在 Redhat 上复制软件源配置
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/"
    mode: "0644"
    force: true
  with_items:
    - "wandisco-git.repo"
    - "mongodb.repo"
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - configure_redhat_sources
  when: common_is_centos_os

- name: 在 Redhat 上导入 GPG 密钥
  ansible.builtin.rpm_key:
    key: http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco
    state: present
  become: true
  become_method: ansible.builtin.sudo
  failed_when: false
  tags:
    - configure_redhat_sources
  when: common_is_centos_os

- name: 在 Ubuntu 上配置开机自动执行
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - configure_rc_local
  when: common_is_linux_os

  block:
    - name: 复制 my-rc-local.service 服务文件
      ansible.builtin.copy:
        src: "rc-local.service"
        dest: "/etc/systemd/system/my-rc-local.service"
        mode: "0755"
        force: true
        backup: false
      failed_when: false
    - name: 复制 /etc/my-rc.local 启动脚本
      ansible.builtin.template:
        src: "rc.local"
        dest: "/etc/my-rc.local"
        mode: "0755"
        force: true
        backup: false
      failed_when: false
    - name: 启动 my-rc-local 服务
      ansible.builtin.service:
        name: "my-rc-local"
        state: "started"
        enabled: true
      failed_when: false
- name: 配置DNS
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - configure_dns
  when: common_is_ubuntu_os
  block:
    - name: "修改DNS"
      ansible.builtin.replace:
        path: "/etc/systemd/resolved.conf"
        regexp: "^#?DNS=.*"
        replace: "DNS=8.8.8.8 114.114.114.114"
    - name: "重启服务"
      ansible.builtin.systemd:
        name: "systemd-resolved"
        state: "restarted"
        enabled: true
        daemon_reload: true
