---
# tasks file for install

- name: create project dir
  file:
    dest: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ HOME_ROOT }}/.ssh"
    - "{{ HOME_ROOT }}/.pip"
    - "{{ GOPATH }}"
    - "{{ PythonProjects }}"
    - "{{ WebProjects }}"
  tags:
    - configure

- name: copy bash_profile script template
  template:
    src: .bash_profile
    dest: "{{ HOME_ROOT }}"
    mode: 0644
    force: true
    backup: true # 进行备份
  tags:
    - configure

- name: copy pip.conf script template
  template:
    src: pip.conf
    dest: "{{ HOME_ROOT }}/.pip"
    mode: 0644
  tags:
    - configure

- name: copy vim configure into home
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ HOME_ROOT }}"
    mode: 0644
    force: false # 避免原主机文件被覆盖
  with_items:
    - .vimrc
  tags:
    - configure

- name: copy ssh config into home
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ HOME_ROOT }}/.ssh"
    mode: 0644
    force: false # 避免原主机文件被覆盖
  with_items:
    - config
    - authorized_keys
  tags:
    - configure

- name: copy virtualbox start/stop script On macOS
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ PACKAGES_ROOT }}"
    mode: 0755
    force: false # 避免原主机文件被覆盖
  with_items:
    - "start_vm.sh"
    - "stop_vm.sh"
    - "replace_config.sh"
  tags:
    - configure
  when: is_mac_os

- name: virtualbox script link to path On macOS
  file:
    src: "{{ PACKAGES_ROOT }}/{{ item }}"
    dest: "/usr/local/bin/{{ item.replace('.sh', '') }}"
    state: link
    force: false # 避免原主机文件被覆盖
  with_items:
    - "start_vm.sh"
    - "stop_vm.sh"
    - "replace_config.sh"
  tags:
    - configure
  when: is_mac_os


- name: copy apt source list on Ubuntu
  copy:
    src: "sources.list"
    dest: "/etc/apt/"
    mode: 0644
    force: true
  tags:
    - configure
  when: is_ubuntu_os

- name: copy repo on Redhat
  copy:
    src: "CentOS-Base.repo"
    dest: "/etc/yum.repos.d/"
    mode: 0644
    force: true
    backup: true
  tags:
    - configure
  when: is_centos_os
