---
- name: check docker installed
  shell: "docker --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_docker
  changed_when: False
  tags:
    - docker

- name: check docker-machine installed
  shell: "docker-machine --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_docker_machine
  changed_when: False
  tags:
    - docker

- name: check docker-compose installed
  shell: "docker-compose --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_docker_compose
  changed_when: False
  tags:
    - docker

- name: copy docker repo on Redhat
  copy:
    src: "{{ role_path }}/files/deploy-docker.repo"
    dest: /etc/yum.repos.d/
    mode: 0644
    force: true
  tags:
    - docker
  when: is_centos_os and installed_of_docker.stdout == "1"

- name: Add docker source on Redhat
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  tags:
    - docker
  when: is_centos_os and installed_of_docker.stdout == "1"

- name: Install docker on Redhat
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - docker-ce
  tags:
    - docker
  when: is_centos_os and installed_of_docker.stdout == "1"

- name: Add gpg key on Ubuntu
  shell: "{{ item }}"
  with_items:
    - apt-get remove docker docker-engine docker.io containerd runc
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - apt-get update
  become: yes
  become_method: sudo
  tags:
    - docker
  when: is_ubuntu_os and installed_of_docker.stdout == "1"

- name: Install docker on Ubuntu
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  tags:
    - docker
  when: is_ubuntu_os and installed_of_docker.stdout == "1"

- name: Install docker on macOS
  shell: "brew cask install {{ item }}"
  with_items:
    - docker
    - docker-completion
    - docker-compose-completion
    - docker-machine-completion
  tags:
    - docker
  when: is_mac_os and installed_of_docker.stdout == "1"

- name: install docker-machine on macOS
  shell: "brew install docker-machine"
  tags:
    - docker
  when: is_mac_os and installed_of_docker_machine.stdout == "1"

- name: install docker-machine on macOS
  shell: "brew install docker-compose"
  tags:
    - docker
  when: is_mac_os and installed_of_docker_compose.stdout == "1"

- name: install docker-compose on Linux
  shell: "{{ item }}"
  with_items:
    - 'curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
    - 'chmod +x /usr/local/bin/docker-compose'
  tags:
    - docker
  when: is_linux_os and installed_of_docker_compose.stdout == "1"

- name: start docker on ubuntu or Redhat
  service:
    name: "docker"
    state: "started"
    enabled: "yes"
  register: log
  ignore_errors: True
  tags:
    - docker
  when: is_linux_os

- name: "macOS修改docker启动配置"
  copy:
    src: mac-daemon.json
    dest: "{{ HOME_ROOT }}/.docker/daemon.json"
    mode: 0644
    force: true
    backup: true # 进行备份
  tags:
    - kubeadm
  when: is_mac_os

- name: "macOS重启Docker"
  shell: osascript -e 'quit app "Docker"' && open -a Docker
  tags:
    - kubeadm
  when: is_mac_os

# - name: "macOS关闭防火墙"
#   shell: launchctl unload /System/Library/LaunchDaemons/com.apple.alf.agent.plist
#   become: yes
#   become_method: sudo
#   tags:
#     - kubeadm
#   when: is_mac_os
