---
- name: check docker installed
  shell: "docker --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_docker
  changed_when: False
  tags:
    - docker

- name: check docker-machine installed
  shell: "docker-machine --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_docker_machine
  changed_when: False
  tags:
    - docker

- name: check docker-compose installed
  shell: "docker-compose --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_docker_compose
  changed_when: False
  tags:
    - docker

- name: Add docker source on Redhat
  shell: "{{ item }}"
  with_items:
    - "rm -f /etc/yum.repos.d/docker-ce.repo"
    - "yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo"
    # - "yum-config-manager --add-repo https://mirrors.aliyun.com/repo/Centos-8.repo"
  tags:
    - docker
  when: is_centos_os and installed_of_docker.stdout == "1"

# 安装containerd
# yum install https://download.docker.com/linux/centos/8/x86_64/stable/Packages/containerd.io-1.6.9-3.1.el8.x86_64.rpm

# 安装container-selinux
# yum install https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/container-selinux-2.124.0-1.gitf958d0c.module_el8.4.0+521+9df8e6d3.noarch.rpm

# 安装docker-ce-rootless-extras
# yum install https://download.docker.com/linux/centos/8/x86_64/stable/Packages/docker-ce-rootless-extras-20.10.0-3.el8.x86_64.rpm

# almalinux 9 docker 无法启动https://github.com/docker/cli/issues/2104
# 编辑 /etc/default/grub 设置 GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200n8 no_timer_check biosdevname=0 net.ifnames=0 cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0"
# dnf install -y grubby && grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
# reboot
- name: Install docker on Redhat
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
    nobest: true
  # yum list docker-ce --showduplicates | grep "^docker" | sort -r
  with_items:
    - docker-ce-cli{{ DOCKER_CLI_VERSION | default('') }}
    - docker-ce{{ DOCKER_VERSION | default('') }}
  tags:
    - docker
  when: is_centos_os and installed_of_docker.stdout == "1"

- name: Add gpg key on Ubuntu
  shell: "{{ item }}"
  with_items:
    - sudo apt-get autoremove -y docker docker.io containerd runc
    - for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
    - sudo install -m 0755 -d /etc/apt/keyrings
    - sudo rm -f /etc/apt/keyrings/docker.gpg
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - sudo chmod a+r /etc/apt/keyrings/docker.gpg
    - |-
      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - sudo apt-get update
  tags:
    - docker
  when: is_ubuntu_os and installed_of_docker.stdout == "1"

- name: Install docker on Ubuntu
  apt:
    pkg: "{{ item }}"
    state: present
    # update_cache: true
  # sudo apt-cache madison docker-ce
  with_items:
    - docker-ce-cli{{ DOCKER_CLI_VERSION | default('') }}
    - docker-ce{{ DOCKER_VERSION | default('') }}
    - containerd.io{{ CONTAINERD_VERSION | default('') }}
  tags:
    - docker
  ignore_errors: True
  become: true
  become_method: sudo
  when: is_ubuntu_os and installed_of_docker.stdout == "1"

- name: Install docker on macOS
  shell: "brew cask install {{ item }}"
  with_items:
    - docker
    - docker-completion
    - docker-compose-completion
    - docker-machine-completion
  tags:
    - docker
  when: is_mac_os and installed_of_docker.stdout == "1"

- name: install docker-machine on macOS
  shell: "brew install docker-machine"
  tags:
    - docker
  when: is_mac_os and installed_of_docker_machine.stdout == "1"

- name: install docker-machine on macOS
  shell: "brew install docker-compose"
  tags:
    - docker
  when: is_mac_os and installed_of_docker_compose.stdout == "1"

- name: install docker-compose on Linux
  shell: "{{ item }}"
  with_items:
    - 'curl -L "https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION | default("v2.24.2") }}/docker-compose-$(uname -s | tr L l)-$(uname -m)" -o /usr/local/bin/docker-compose'
    - 'chmod +x /usr/local/bin/docker-compose'
  ignore_errors: True
  become: true
  become_method: sudo
  tags:
    - docker
  when: is_linux_os and installed_of_docker_compose.stdout == "1"

- name: start docker on ubuntu or Redhat
  service:
    name: "docker"
    state: "started"
    enabled: "yes"
  register: log
  ignore_errors: True
  tags:
    - docker
  when: is_linux_os

- name: "macOS修改docker启动配置"
  copy:
    src: mac-daemon.json
    dest: "{{ HOME_ROOT }}/.docker/daemon.json"
    mode: 0644
    force: true
    backup: true # 进行备份
  tags:
    - docker
  when: is_mac_os

- name: "macOS重启Docker"
  shell: osascript -e 'quit app "Docker"' && open -a Docker
  tags:
    - docker
  when: is_mac_os

# - name: "macOS关闭防火墙"
#   shell: launchctl unload /System/Library/LaunchDaemons/com.apple.alf.agent.plist
#   become: true
#   become_method: sudo
#   tags:
#     - docker
#   when: is_mac_os
