---
- name: check docker installed
  shell: "docker --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_docker
  changed_when: False
  tags:
    - docker

- name: check docker-machine installed
  shell: "docker-machine --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_docker_machine
  changed_when: False
  tags:
    - docker

- name: check docker-compose installed
  shell: "docker-compose --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_docker_compose
  changed_when: False
  tags:
    - docker

- name: copy docker repo on Redhat
  copy:
    src: "{{ role_path }}/files/deploy-docker.repo"
    dest: /etc/yum.repos.d/
    mode: 0644
    force: true
  tags:
    - docker
  when: ansible_os_family == "RedHat" and installed_of_docker.stdout == "1"

- name: Add docker source on Redhat
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  tags:
    - docker
  when: ansible_os_family == "RedHat" and installed_of_docker.stdout == "1"

- name: Install docker on Redhat
  yum:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - docker-ce
  tags:
    - docker
  when: ansible_os_family == "RedHat" and installed_of_docker.stdout == "1"

- name: Add gpg key on Ubuntu
  shell: "{{item}}"
  with_items:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  become: yes
  become_method: sudo
  tags:
    - docker
  when: ansible_os_family == "Debian" and installed_of_docker.stdout == "1"

- name: Install docker on Ubuntu
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - docker.io
  tags:
    - docker
  when: ansible_os_family == "Debian" and installed_of_docker.stdout == "1"

- name: Install docker on macOS
  shell: "brew cask install {{item}}"
  with_items:
    - docker
    - docker-completion
    - docker-compose-completion
    - docker-machine-completion
  tags:
    - docker
  when: ansible_os_family == "Darwin" and installed_of_docker.stdout == "1"

- name: install docker-machine on macOS
  shell: "brew install docker-machine"
  tags:
    - docker
  when: ansible_os_family == "Darwin" and installed_of_docker_machine.stdout == "1"

- name: install docker-machine on macOS
  shell: "brew install docker-compose"
  tags:
    - docker
  when: ansible_os_family == "Darwin" and installed_of_docker_compose.stdout == "1"

- name: install docker-machine on Ubuntu
  shell: "{{item}}"
  with_items:
    - 'curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
    - 'chmod +x /usr/local/bin/docker-compose'
  tags:
    - docker
  when: ansible_os_family == "Debian" and installed_of_docker_compose.stdout == "1"

- name: start docker on ubuntu or Redhat
  service: name={{item.name}} state={{item.state}} enabled={{item.enabled}}
  register: log
  ignore_errors: True
  with_items:
    - name: 'docker'
      enabled: 'yes'
      state: 'started'
  tags:
    - docker
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

# TODO: Mac 启动服务
