---
- name: 创建 Golang 目录
  ansible.builtin.file:
    dest: "{{ install_gopath }}/{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - bin
    - src
    - pkg
  tags:
    - golang

- name: 检查 Linux 上是否已有 Golang 安装包
  ansible.builtin.shell: "test -f {{ install_go_package_path_on_linux }} && echo 0 || echo 1"
  register: install_existing_of_go_on_linux
  changed_when: false
  tags:
    - golang
  when: common_is_linux_os

- name: 检查 macOS 上是否已有 Golang 安装包
  ansible.builtin.shell: "test -f {{ install_go_package_path_on_mac }} && echo 0 || echo 1"
  register: install_existing_of_go_on_mac
  changed_when: false
  tags:
    - golang
  when: common_is_intel_mac_os

- name: 检查 Golang 是否已安装
  ansible.builtin.shell: "test -d {{ common_goroot }} && echo 0 || echo 1"
  register: install_installed_of_go
  changed_when: false
  tags:
    - golang

- name: 安装 Golang
  tags:
    - golang
  block:
    - name: 在 Linux 上下载 Golang 安装包
      ansible.builtin.get_url:
        url: "{{ install_go_download_url_on_linux }}"
        dest: "{{ install_go_package_path_on_linux }}"
        force: false
        mode: "0644"
      when: common_is_linux_os and install_existing_of_go_on_linux.stdout == "1"

    - name: 在 macOS 上下载 Golang 安装包
      ansible.builtin.get_url:
        url: "{{ install_go_download_url_on_mac }}"
        dest: "{{ install_go_package_path_on_mac }}"
        force: false
        mode: "0644"
      when: common_is_intel_mac_os and install_existing_of_go_on_mac.stdout == "1"

    - name: 在 Linux 上解压 Golang
      ansible.builtin.unarchive:
        src: "{{ install_go_package_path_on_linux }}"
        dest: "{{ common_soft_install_root }}"
        remote_src: true
      become: true
      become_method: ansible.builtin.sudo
      when: common_is_linux_os and install_installed_of_go.stdout == "1"

    - name: 在 macOS 上解压 Golang
      ansible.builtin.unarchive:
        src: "{{ install_go_package_path_on_mac }}"
        dest: "{{ common_soft_install_root }}"
        remote_src: true
      become: true
      become_method: ansible.builtin.sudo
      when: common_is_intel_mac_os and install_installed_of_go.stdout == "1"
