---
- name: 创建 Java 安装目录
  ansible.builtin.file:
    dest: "{{ common_java_home }}"
    state: directory
    mode: "0755"
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - java
  when: common_is_linux_os

- name: 检查 Linux 上是否已有 Java 安装包
  ansible.builtin.shell: "test -f {{ install_java_package_path_on_linux }} && echo 0 || echo 1"
  register: install_existing_of_java_on_linux
  changed_when: false
  tags:
    - java
  when: common_is_linux_os

- name: 输出 Linux Java 安装包检查结果
  ansible.builtin.debug:
    msg: "Linux Java 安装包 {{ '已存在' if install_existing_of_java_on_linux.stdout == '0' else '不存在' }}"
  tags:
    - java
  when: common_is_linux_os

- name: 检查 Java 是否已安装
  ansible.builtin.shell: "java --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: install_installed_of_java
  changed_when: false
  tags:
    - java
  when: common_is_linux_os

- name: 输出 Java 检查结果
  ansible.builtin.debug:
    msg: "Java {{ '已安装' if install_installed_of_java.stdout == '0' else '未安装' }}"
  tags:
    - java
  when: common_is_linux_os

- name: 安装 Java
  tags:
    - java

  block:
    - name: 在 Linux 上下载 Java 安装包
      ansible.builtin.get_url:
        url: "{{ install_java_download_url_on_linux }}"
        dest: "{{ install_java_package_path_on_linux }}"
        force: false
        mode: "0644"
      when: (common_is_linux_os) and install_existing_of_java_on_linux.stdout == "1"

    - name: 在 Linux 上解压 Java
      ansible.builtin.unarchive:
        src: "{{ install_java_package_path_on_linux }}"
        dest: "{{ common_java_home }}"
        remote_src: true
        extra_opts: ["--strip-components=1"]
      become: true
      become_method: ansible.builtin.sudo
      when: (common_is_linux_os) and install_installed_of_java.stdout == "1"
- name: 检查 Linux 上是否已有 Maven 安装包
  ansible.builtin.shell: "test -f {{ install_mvn_package_path_on_linux }} && echo 0 || echo 1"
  register: install_existing_of_mvn_on_linux
  changed_when: false
  tags:
    - java
  when: common_is_linux_os

- name: 输出 Linux Maven 安装包检查结果
  ansible.builtin.debug:
    msg: "Linux Maven 安装包 {{ '已存在' if install_existing_of_mvn_on_linux.stdout == '0' else '不存在' }}"
  tags:
    - java
  when: common_is_linux_os

- name: 检查 Maven 是否已安装
  ansible.builtin.shell: "mvn --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: install_installed_of_mvn
  changed_when: false
  tags:
    - java
  when: common_is_linux_os

- name: 输出 Maven 检查结果
  ansible.builtin.debug:
    msg: "Maven {{ '已安装' if install_installed_of_mvn.stdout == '0' else '未安装' }}"
  tags:
    - java
  when: common_is_linux_os

- name: 安装 Maven
  tags:
    - java
  block:
    - name: 在 Linux 上下载 Maven 安装包
      ansible.builtin.get_url:
        url: "{{ install_mvn_download_url_on_linux }}"
        dest: "{{ install_mvn_package_path_on_linux }}"
        force: false
        mode: "0644"
      when: (common_is_linux_os) and install_existing_of_mvn_on_linux.stdout == "1"

    - name: 创建 Maven 安装目录
      ansible.builtin.file:
        path: "{{ common_mvn_home }}"
        state: directory
        mode: "0755"
      when: (common_is_linux_os) and install_installed_of_mvn.stdout == "1"

    - name: 在 Linux 上解压 Maven
      ansible.builtin.unarchive:
        src: "{{ install_mvn_package_path_on_linux }}"
        dest: "{{ common_mvn_home }}"
        remote_src: true
        extra_opts: ["--strip-components=1"]
      when: (common_is_linux_os) and install_installed_of_mvn.stdout == "1"
