---
- name: create java home
  file:
    dest: "{{JAVA_HOME}}"
    state: directory
    mode: 0755
  tags:
    - java
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: check existing java packages on Linux
  shell: "test -f {{JAVA_PACKAGE_PATH_ON_LINUX}} && echo 0 || echo 1"
  register: existing_of_java_on_linux
  changed_when: False
  tags:
    - java
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: check java installed
  shell: "java --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_java
  changed_when: False
  tags:
    - java
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: install java
  block:
    - name: download java packages on Linux
      get_url:
        url: "{{JAVA_DOWNLOAD_URL_ON_LINUX}}"
        dest: "{{JAVA_PACKAGE_PATH_ON_LINUX}}"
        force: false
      when: (ansible_os_family == "RedHat" or ansible_os_family == "Debian") and existing_of_java_on_linux.stdout == "1"
    
    - name: unarchive java on Linux
      unarchive:
        src: "{{JAVA_PACKAGE_PATH_ON_LINUX}}"
        dest: "{{JAVA_HOME}}"
        remote_src: true
        extra_opts: ['--strip-components=1']
      when: (ansible_os_family == "RedHat" or ansible_os_family == "Debian") and installed_of_java.stdout == "1"
  tags:
    - java
