---
- include: configure.yml
- include: initialize.yml
- include: zsh.yml
- include: python.yml
- include: virtualenv.yml
- include: docker.yml
- include: golang.yml
- include: java.yml
- include: nodejs.yml
- include: k3s.yml

- name: check pyenv installed
  shell: "test -d {{ PYENV_ROOT }} && echo 0 || echo 1"
  register: installed_of_pyenv
  changed_when: False
  tags:
    - pyenv

- name: download pyenv
  git:
    repo: git://github.com/pyenv/pyenv
    dest: "{{ PYENV_ROOT }}"
    accept_hostkey: true
  when: installed_of_pyenv.stdout == "1"
  tags:
    - pyenv

- name: check existing ansible
  shell: "ansible --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: existing_of_ansible
  changed_when: False
  tags:
    - ansible

- name: install ansible
  shell: "pip install ansible"
  tags:
    - ansible
  when: existing_of_ansible.stdout == "1"
