---
- include: initialize.yml
- include: zsh.yml
- include: docker.yml
- include: golang.yml
- include: nodejs.yml

- name: install ansible
  shell: "pip install ansible -i {{PIP_INDEX_URL}}"
  tags:
    - ansible
