---
- include_tasks: configure.yml
- include_tasks: initialize.yml
- include_tasks: zsh.yml
- include_tasks: pyenv.yml
- include_tasks: python.yml
- include_tasks: virtualenv.yml
- include_tasks: docker.yml
- include_tasks: golang.yml
- include_tasks: java.yml
- include_tasks: nodejs.yml
- include_tasks: rbenv.yml

- name: check existing ansible
  shell: "ansible --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: existing_of_ansible
  changed_when: False
  tags:
    - ansible

- name: install ansible
  shell: "pip install ansible"
  tags:
    - ansible
  when: existing_of_ansible.stdout == "1"
