---
- name: update bashrc configuare
  shell: "{{item}}"
  with_items:
    - "sed -ie '/export NVM_DIR=\"{{HOME_ROOT}}\/.nvm\"/d' {{HOME_ROOT}}/.bashrc"
    - "sed -ie '/\\\"$NVM_DIR\\/nvm.sh\\\"/d' {{HOME_ROOT}}/.bashrc"
    - "sed -ie '/\\\"$NVM_DIR\\/bash_completion\\\"/d' {{HOME_ROOT}}/.bashrc"
  tags:
    - nodejs

- name: create nvm dir
  file:
    dest: "{{item}}"
    state: directory
    mode: 0755
  with_items:
    - "{{HOME_ROOT}}/.nvm"
  tags:
    - nodejs


- name: install nodejs
  block:
    - name: install npm
      shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

    - name: install nodejs
      shell: "source {{HOME_ROOT}}/.bashrc && nvm install v11.4.0"
  tags:
    - nodejs
