---

- name: check n installed
  shell: "n --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_n
  changed_when: False
  tags:
    - nodejs

- name: check node installed
  shell: "node -v >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_node
  changed_when: False
  tags:
    - nodejs

- name: install nodejs
  block:
    - name: install n
      shell: "export N_PREFIX=/usr/local/n && curl -L https://bit.ly/n-install | bash -s -- -y {{ NODE_VERSION }}"
      when: installed_of_n.stdout == "1"
      tags:
        - nodejs

    - name: change directory mode
      shell: "chown -R $(whoami):$(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share"
      when: installed_of_node.stdout == "1"
      tags:
        - nodejs
      become: true
      become_method: sudo

    - name: install node
      shell: "/usr/local/n/bin/n {{ NODE_VERSION }}"
      when: installed_of_node.stdout == "1"
      tags:
        - nodejs
      become: true
      become_method: sudo

    - name: install yarn
      shell: "npm install -g yarn"
      when: installed_of_node.stdout == "1"
      tags:
        - nodejs
      become: true
      become_method: sudo
  tags:
    - nodejs
