---
- name: check nvm installed
  shell: "test -d {{HOME_ROOT}}/.nvm && echo 0 || echo 1"
  register: installed_of_nvm
  changed_when: False
  tags:
    - nodejs

- name: check npm installed
  shell: "npm --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_npm
  changed_when: False
  tags:
    - nodejs

- name: check cnpm installed
  shell: "cnpm --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_cnpm
  changed_when: False
  tags:
    - nodejs

- name: check node installed
  shell: "node -v >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_node
  changed_when: False
  tags:
    - nodejs

- name: install nodejs
  block:
    - name: create nvm dir
      file:
        dest: "{{HOME_ROOT}}/.nvm"
        state: directory
        mode: 0755
      when: installed_of_nvm.stdout == "1"

    - name: install npm
      shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
      when: installed_of_npm.stdout == "1"

    - name: install nodejs
      shell: ". {{HOME_ROOT}}/.bash_profile && nvm install v11.4.0"
      when: installed_of_node.stdout == "1"

    - name: install cnpm
      shell: ". {{HOME_ROOT}}/.bash_profile && npm install -g cnpm --registry=https://registry.npm.taobao.org"
      when: installed_of_cnpm.stdout == "1"
  tags:
    - nodejs
