---
- name: check pyenv installed
  shell: "test -d {{ PYENV_ROOT }} && echo 0 || echo 1"
  register: installed_of_pyenv
  changed_when: False
  tags:
    - pyenv

- name: download pyenv
  git:
    repo: "{{ PYENV_REPOSITORY }}"
    dest: "{{ PYENV_ROOT }}"
    accept_hostkey: true
  when: installed_of_pyenv.stdout == "1"
  tags:
    - pyenv

- name: pull pyenv
  block:
    - name: repository set-url
      git_config:
          repo: "{{ PYENV_ROOT }}"
          scope: "local"
          name: "remote.origin.url"
          value: "{{ PYENV_REPOSITORY }}"
    - name: pull repository
      git:
        repo: "{{ PYENV_REPOSITORY }}"
        dest: "{{ PYENV_ROOT }}"
        update: yes
        version: master
  when: installed_of_pyenv.stdout == "0"
  tags:
    - pyenv