---
- name: install python
  shell: 'if [ $(uv python list --only-installed {{ item.version }} | grep -v "<download" | wc -l) -gt 0 ]; then echo {{ item.version }} is installed; else uv python install {{ item.version }}; fi'
  with_items: "{{ VIRTUAL_ENVS }}"
  tags:
    - python
