---
- name: check eisting pyconcreate
  shell: "test -f {{ PYCONCREATE_PATH }} && echo 0 || echo 1"
  register: existing_of_pyconcreate
  changed_when: False
  tags:
    - pyconcreate

- name: download pyconcreate
  get_url:
    url: "https://github.com/Falldog/pyconcrete/archive/{{ PYCONCREATE_VERSION }}.tar.gz"
    dest: "{{ PYCONCREATE_PATH }}"
    force: false
  tags:
    - pyconcreate
  when: existing_of_pyconcreate is defined and existing_of_pyconcreate.stdout == "1"

- name: check pyconcrete unarchive
  shell: "test -d {{ PYCONCREATE_DIRECTORY }} && echo 0 || echo 1"
  register: unarchive_of_pyconcrete
  tags:
    - pyconcreate

- name: unarchive pyconcrete
  shell: "tar -zxvf {{ PYCONCREATE_PATH }} -C {{ HOME_ROOT }}"
  register: result_of_unarchive_pyconcrete
  tags:
    - pyconcreate
  when: unarchive_of_pyconcrete is defined and unarchive_of_pyconcrete.stdout == "1"

- name: make env
  include_tasks: .virtualenv.yml
  with_items: "{{ VIRTUAL_ENVS }}"
  tags:
    - virtualenv
    - pyconcreate
