---
- name: check zsh installed
  shell: "zsh --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_zsh
  changed_when: False
  tags:
    - zsh

- name: check oh-my-zsh installed
  shell: "test -d {{HOME_ROOT}}/.oh-my-zsh/ && echo 0 || echo 1"
  register: installed_of_oh_my_zsh
  changed_when: False
  tags:
    - zsh

- name: check zsh-autosuggestions installed
  shell: "test -d {{HOME_ROOT}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions && echo 0 || echo 1"
  register: installed_of_oh_my_zsh_autosuggestions
  changed_when: False
  tags:
    - zsh

- name: install zsh on Redhat
  yum:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - zsh
  tags:
    - zsh
  when: ansible_os_family == "RedHat" and installed_of_zsh.stdout == "1"

- name: install zsh on Ubuntu
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - zsh
  tags:
    - zsh
  when: ansible_os_family == "Debian" and installed_of_zsh.stdout == "1"

- name: install zsh on macOS
  shell: 'if [ $(brew list | grep {{item}} | wc -l) == "0" ]; then brew install {{item}}; else echo {{item}} is installed; fi'
  with_items:
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
  tags:
    - zsh
  when: ansible_os_family == "Darwin" and installed_of_zsh.stdout == "1"

- name: install oh-my-zsh
  block:
    - name: download oh-my-zsh
      shell:
        cmd: |
          sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)" <<EOF
          exit
          EOF
      when: installed_of_oh_my_zsh.stdout == "1"

    - name: download zsh autosuggestions
      git:
        repo: git://github.com/zsh-users/zsh-autosuggestions
        dest: "{{HOME_ROOT}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        accept_hostkey: true
      when: installed_of_oh_my_zsh_autosuggestions.stdout == "1"
  tags:
    - zsh

- name: change terminal
  shell: "chsh -s /bin/zsh {{ansible_ssh_user}}"
  become: yes
  become_method: sudo
  tags:
    - zsh

- name: copy zshrc template into home
  template:
    src: .zshrc
    dest: "{{HOME_ROOT}}"
    mode: 0644
    force: true
  tags:
    - zsh

- name: configuare zsh on Linux
  shell: "sed -i '3,6d' {{HOME_ROOT}}/.bash_profile"
  changed_when: True
  tags:
    - zsh
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

# mac的sed用法有区别
- name: configuare zsh on macOS
  shell: "sed -i \"\" '3,6d' {{HOME_ROOT}}/.bash_profile"
  changed_when: True
  tags:
    - zsh
  when: ansible_os_family == "Darwin"

- name: update bash_profile configuare
  lineinfile:
    dest: "{{HOME_ROOT}}/.bash_profile"
    state: absent
    regexp: "{{item}}"
  with_items:
    - 'export PS1="'
  changed_when: True
  tags:
    - zsh