---
- name: check zsh installed
  shell: "zsh --version >/dev/null 2>&1 && echo 0 || echo 1"
  register: installed_of_zsh
  changed_when: False
  tags:
    - zsh

- name: check oh-my-zsh installed
  shell: "test -d {{ HOME_ROOT }}/.oh-my-zsh/ && echo 0 || echo 1"
  register: installed_of_oh_my_zsh
  changed_when: False
  tags:
    - zsh

- name: check zsh-autosuggestions installed
  shell: "test -d {{ HOME_ROOT }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions && echo 0 || echo 1"
  register: installed_of_oh_my_zsh_autosuggestions
  changed_when: False
  tags:
    - zsh

- name: install zsh on Redhat
  yum:
    name: "zsh"
    state: present
    update_cache: true
  # shell: yum install -y zsh
  tags:
    - zsh
  when: is_centos_os and installed_of_zsh.stdout == "1"

- name: install zsh on Ubuntu
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - zsh
  tags:
    - zsh
  become: true
  become_method: sudo
  when: is_ubuntu_os and installed_of_zsh.stdout == "1"

- name: install zsh on macOS
  shell: 'if [ $(brew list | grep {{ item }} | wc -l) == "0" ]; then brew install {{ item }}; else echo {{ item }} is installed; fi'
  with_items:
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
  tags:
    - zsh
  when: is_mac_os and installed_of_zsh.stdout == "1"

- name: install oh-my-zsh
  block:
    - name: download oh-my-zsh
      shell:
        cmd: |
          sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)" <<EOF
          exit
          EOF
      when: installed_of_oh_my_zsh.stdout == "1"

    - name: download zsh autosuggestions
      git:
        repo: git@github.com:zsh-users/zsh-autosuggestions
        dest: "{{ HOME_ROOT }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        accept_hostkey: true
      when: installed_of_oh_my_zsh_autosuggestions.stdout == "1"
  tags:
    - zsh

- name: change terminal
  shell: "chsh -s /bin/zsh {{ ansible_user_id }}"
  become: true
  become_method: sudo
  tags:
    - zsh

- name: copy zshrc template into home
  template:
    src: .zshrc
    dest: "{{ HOME_ROOT }}"
    mode: 0644
    force: true
    backup: true # 进行备份
  tags:
    - zsh

- name: update bash_profile configuare
  lineinfile:
    dest: "{{ HOME_ROOT }}/.bash_profile"
    state: absent
    regexp: "{{ item }}"
  with_items:
    - 'export PS1="'
  changed_when: True
  tags:
    - zsh